### PR TITLE
Fix Map DataType fields are not populated with inherited values

### PR DESCRIPTION
**Pull request by gianluca-piccolo-wuerth**
This pull request is related to this issue: #3 Map DataType fields are not populated with inherited values

I fixed this issue, please if you don't like my solution tell me how it should be fixed for you.

Thanks
Gianluca

### CODE REVIEW

**Comment by nbuchwitz** [comment]
Thanks for your PR. I would have loved to see you as the author of the placeholder feature as you were the one who reported the issue, but I choose a simpler implementation in a1e8399d3e0788b03b74267744ac7eb15a5217e6 .

**Comment by gianluca-piccolo-wuerth** [comment]
I tried that implementation but it doesn't work because it shows a truncated string as you can't provide a parent object from the custom form element.

screenshot from 2018-11-23 17-37-33

**Comment by nbuchwitz** [comment]
So you want to see from which template the value is inherited? This should be easy as it is passed as placeholder (but truncated by the form field)

**Comment by gianluca-piccolo-wuerth** [comment]
I didn't see that, sorry.  What do you mean for is truncated by the form field? I gave a look at it and I found that the placeholder attribute is truncated because the name of the parent template is wrapped around double quotes. I converted properly $this->element->getAttrib('placeholder') with htmlspecialchars() and it worked fine. Do you thing it's a good solution? I can send you the pull request.

**Comment by nbuchwitz** [comment]
Perfect! I'd love to see a PR for this. 

Am 23. November 2018 19:57:57 MEZ schrieb gianluca-piccolo-wuerth <notifications@github.com>:
>I didn't see that, sorry.  What do you mean for is truncated by the
>form field? I gave a look at it and I found that the placeholder
>attribute is truncated because the name of the parent template is
>wrapped around double quotes. I converted properly
>$this->element->getAttrib('placeholder') with htmlspecialchars() and it
>worked fine. Do you thing it's a good solution? I can send you the pull
>request.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/nbuchwitz/icingaweb2-module-mapDatatype/pull/4#issuecomment-441303763

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by gianluca-piccolo-wuerth** [comment]
Done!

**Pull request closed without merging**
